version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: wecount-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: WeCountDb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
